services:
  - type: web
    name: online-library-ms
    runtime: php
    plan: free
    region: oregon
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: RENDER
        value: "true"
    repo: https://github.com/jatinpitrola-eng/online-library-management-system
    branch: main